name: build-dual-frontends

on:
  pull_request:
  push:
    branches: [ feat/ultimate-docker-firebase ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C apps/patient-spa build
      - run: pnpm -C apps/practitioner-spa build
      - run: pnpm -C functions build || true


