name: deploy-multi-hosting

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Build SPAs
        run: |
          pnpm -C apps/patient-spa build
          pnpm -C apps/practitioner-spa build
      - name: Deploy Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: neuronutrition-app
          channelId: live


